# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ttt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ttt.proto',
  package='ttt',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tttt.proto\x12\x03ttt\"=\n\x0bPlayRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\r\n\x05\x62oard\x18\x02 \x01(\t\x12\x0e\n\x06player\x18\x03 \x01(\x05\"$\n\x0cPlayResponse\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x32\x31\n\x02\x41I\x12+\n\x04Play\x12\x10.ttt.PlayRequest\x1a\x11.ttt.PlayResponseb\x06proto3'
)




_PLAYREQUEST = _descriptor.Descriptor(
  name='PlayRequest',
  full_name='ttt.PlayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='ttt.PlayRequest.game_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='board', full_name='ttt.PlayRequest.board', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player', full_name='ttt.PlayRequest.player', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=79,
)


_PLAYRESPONSE = _descriptor.Descriptor(
  name='PlayResponse',
  full_name='ttt.PlayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ttt.PlayResponse.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='ttt.PlayResponse.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['PlayRequest'] = _PLAYREQUEST
DESCRIPTOR.message_types_by_name['PlayResponse'] = _PLAYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayRequest = _reflection.GeneratedProtocolMessageType('PlayRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLAYREQUEST,
  '__module__' : 'ttt_pb2'
  # @@protoc_insertion_point(class_scope:ttt.PlayRequest)
  })
_sym_db.RegisterMessage(PlayRequest)

PlayResponse = _reflection.GeneratedProtocolMessageType('PlayResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLAYRESPONSE,
  '__module__' : 'ttt_pb2'
  # @@protoc_insertion_point(class_scope:ttt.PlayResponse)
  })
_sym_db.RegisterMessage(PlayResponse)



_AI = _descriptor.ServiceDescriptor(
  name='AI',
  full_name='ttt.AI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=119,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='Play',
    full_name='ttt.AI.Play',
    index=0,
    containing_service=None,
    input_type=_PLAYREQUEST,
    output_type=_PLAYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AI)

DESCRIPTOR.services_by_name['AI'] = _AI

# @@protoc_insertion_point(module_scope)
